### ISSUE TITLE
Issue with default value

### ISSUE THREAD

**Issue by ursathi** [gasparnagy/SpecFlow.FsCheck#1]
Hi gasparnagy, 
         First of all thank you for such a wonderful add-on. However, looks like I am facing an issue. As I am new to property based testing, just want to know whether I am doing the things correctly. Let me explain the issue.

I have a scenario in which I want to check the value is in between two numbers, say 60 to 80. Below is my constraint.

[StepArgumentTransformation("Sixty and Eighty")]
        public int BetweenSixtyAndEighty()
        {
            return AsParam("60to80", Gen.Choose(61, 79));
        }

When I run the test case, first call always produces 0. Upon analysing, AsParam returns default(TArg) for the first call, which is 0 for int. And, the ActualParamDictionary instantiated only after the first run, which only will produce the actual values between 60 & 80. As the first run always ends up with 0, my validation too fails, since it is expecting a value from 61 to 79.

Could you help me to resolve the issue? In case you need more details, please let me know.

**Comment by gasparnagy** [comment]
@ursathi that's strange... The implementation should work in the following way.

First there is a "dry-run" or configuration-run: all steps are evaluated, including the step argument transformations, but the actual step definitions are not executed. So in this run it does not matter what value the transformation returns, hence we just use `default(TArg)`. 

Once the configuration run is over, the steps evaluated again multiple times, with the values coming from the generated ranges.

So the fact, that you see a 0 for the first call is not a problem, but normally in this case the step definition that validates the value should not run, so you should not see an error.

Could you please confirm that the step definition is really executed with the 0 values?

**Comment by ursathi** [comment]
@gasparnagy.. Yours is a super quick response.

Yes... with the default value, the step definition is executed. The breakpoint is hit in Given, When, Then methods. Even that is simulated in the Addition sample you provided. In the AnyNumber constraint, I changed the return as follows
return AsParam("any", Gen.Choose(1, 100));

Then, in Addition.Add method, I added the below line (for testing purpose)
if (op1 == 0)
      return 1;

The PropertyBased - Identity property test failed. And, first few lines of the output is below

Test Name:	PropertyBased_IdentityProperty
Test Outcome:	Failed
Result Message:	Assert.AreEqual failed. Expected:<0>. Actual:<1>.
Result StandardOutput:	
Given I have entered any number into the calculator
-> done: AdditionSteps.Given_I_have_entered_NUMBER_into_the_calculator(0) (0.0s)
And I have entered 0 into the calculator
-> done: AdditionSteps.Given_I_have_entered_NUMBER_into_the_calculator(0) (0.0s)
When I press add
-> done: AdditionSteps.When_I_press_add() (0.0s)
Then the result should be the first number on the screen
-> error: Assert.AreEqual failed. Expected:<0>. Actual:<1>. 
Given I have entered any number into the calculator
-> done: AdditionSteps.Given_I_have_entered_NUMBER_into_the_calculator(56) (0.0s)
And I have entered 0 into the calculator
-> done: AdditionSteps.Given_I_have_entered_NUMBER_into_the_calculator(0) (0.0s)
When I press add
-> done: AdditionSteps.When_I_press_add() (0.0s)
Then the result should be the first number on the screen
-> done: AdditionSteps.Then_the_result_should_be_EXPECTEDRESULT_on_the_screen(56) (0.0s)
0:
56

Please let me know, if I am doing anything wrong

**Comment by gasparnagy** [comment]
@ursathi it seems this was a bug... I have fixed it now. I will create a new NuGet package tomorrow.

**Comment by ursathi** [comment]
@gasparnagy Wow.. Cool. Tested with the source code. Working as expected. Thank you so much

**Comment by gasparnagy** [comment]
@ursathi The version with the fix is available from NuGet.org

**Comment by ursathi** [comment]
Fantastic @gasparnagy. Tested with nuget package as well. Thanks
