### ISSUE TITLE
.Net core support?

### ISSUE THREAD

**Issue by ursathi** [gasparnagy/SpecFlow.FsCheck#2]
@gasparnagy would it be possible to share your road map for .net core support? Of course, I understand that it depends on FSCheck, which in turn is waiting for Fsharp.Core. However, once they are ready, shall we expect SpecFlow.FsCheck too will provide support?

**Comment by gasparnagy** [comment]
@ursathi This addon is pretty simple and does not use any .NET infrastructure that would not be available in .NET Core. So once the dependencies are converted, this can be also converted easily. 
In addition to the FsCheck, we also need a .NET Core support for SpecFlow, but hopefully that will also come soon.

**Comment by ursathi** [comment]
@gasparnagy Thanks for your update. Let me reopen this issue, when (and if) it is needed then.
